### ISSUE TITLE
Odd things in north devon reference ranges

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#127]
* The top of the age range for IGG is 45 - correct?
* Several tests have null age ranges (e.g. GLU, IGA, TEST)
* LH has a reference range for age 18-120 that starts at null. Should this be zero?
* HCG has null reference ranges for females - does this just mean women shouldn't be tested for this?
* Ditto FSH2 but for men.

The last two are probably fine, just sense-checking.

**Comment by HelenCEBM** [comment]
- The top of the age range for IGG is 45 - correct? - No, corrected
- Several tests have null age ranges (e.g. GLU, IGA, TEST) - Corrected
- The other three tests (LH, HCG, FSH2) have no ref ranges for adult females (they are cyclical)

**Comment by sebbacon** [comment]
For `LH`, the odd thing is that it *starts* at null and *ends* at 1.7; it would make sense if like `FSH` if *both* were null for adult females...?

**Comment by HelenCEBM** [comment]
![image](https://user-images.githubusercontent.com/24392156/71083305-9e1b1580-218a-11ea-9043-9f12ae2fbde0.png)

**Comment by HelenCEBM** [comment]
Note the column orders differ between trusts so the outputs can look confusing. But presumably this is fine?

**Comment by sebbacon** [comment]
Oh I see, yes, that looks fine thanks!
