### ISSUE TITLE
Ensure no duplicates in test names in code mapping spreadsheet

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#132]
Per https://github.com/ebmdatalab/openpath-dash/issues/129#issuecomment-566186959, `Glucose` and `Platelet Count` both appear twice in as names in the test mapping spreadsheet.

If they are really different tests, they should have different names; if they are the same tests, then they should be mapped.

Note col D "show in app?" - we only import rows where this is `TRUE`, so if the apparent duplicates shouldn't be imported then we can set this to `FALSE`, alternatively.

**Comment by HelenCEBM** [comment]
Platelet count was incorrectly mapped to an incorrect code as well as the correct one, fixed. 

I've been through the duplicate Read codes and amended as follows:

Read code | test name | comment
-- | -- | --
46M7. | urine creatinine | removed UCRR and UCR1 from devon (v low test counts, not sure if same or different)
43GX. | endomysium antibodies | removed in favour of 2 more specific codes for IgA and IgG version
43GY. | ANCA, PANC and CANC | ASSUME that ANCA is the test, p-ANC is positive and c-ANC negative. ND used to report ANCA, now only PANC and CANC, whereas Cornwall report all 3.
4482 | cortisol | removed CORS and CORD from devon code lists (not sure what they mean and don't map to other trusts
479.. | 3 distinct names | fine
451L. | AKI levels | no change
44g.. | GLU, GLUX and csf-GLU  (North Devon) | CSF-GLU seems to be alternative code for CGLU (488..). Also removed row for GLUX and added as alternative code for GLU (poss different test method, but only one ref range) * see image below
44N.. | electrophoresis: EPH and EPHs | added EPHS as alternative to EPH (though they seem distinct we don't show them anyway)
44CF. | Beta2 microglobulin | 2 codes for North devon, rationalised
43m3. | ANA and ANA Titre | removed read code from ANA titre
43J5. | IGA and IGAT | removed read code from IGA titre
43c6. | rheumatoid factor | 2 codes for North Devon, rationalised


![image](https://user-images.githubusercontent.com/24392156/71175489-9a0cf780-225f-11ea-8631-5413ccd69182.png)
