### ISSUE TITLE
Solve the "All tests" problem

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#174]
The thing where selecting something other than "all" retains all is, predictably, very confusing

**Comment by HelenCEBM** [comment]
Agree people found this confusing / cumbersome. Same goes for "All CCGs" and "All labs". 

Can they be blank by default when no filtered is applied? (as per the "highlight" option)
![image](https://user-images.githubusercontent.com/24392156/75438787-7bf30000-5950-11ea-811b-5d97d0ace98e.png)
