### ISSUE TITLE
There should be some indication of what's going on when there's no lines

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#177]
It is possible to lose practice lines on a chart, though I can't quite remember how.

According to my notes, one way is switching denominators.  @HelenCEBM had another.

There should at least be some kind of a warning about this.

**Comment by HelenCEBM** [comment]
If you select L83044 from the landing page there is only a median line on the practice dashboards, no line for that practice

**Comment by sebbacon** [comment]
I think this is solved by not hiding low-prescribing practices by default - which I've done
