### ISSUE TITLE
The CCG and Lab filters don't make intuitive sense

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#178]
When viewing with a practice hat on, what does it mean to filter by lab, etc? Confused everyone.

**Comment by HelenCEBM** [comment]
I don't think my testers found this overly confusing, but:
- although the list of practices to choose from had the filter applied, it wasn't clear that was working properly as you could still select practices with no data (or rather v low numbers - no one noticed they could toggle them on with the checkbox) - similar problem to #177. 
- one GP wanted to look at PCN to view the most familiar comparator organisations with similar populations etc.

**Some options:**
- Only easy semi-fix I can think of is to rename the dropdowns, replacing the word "Filter"? Could use "Show only" or "Limit to" if these might be more clear? Could mention "subset of practices" or "smaller geographical region".
- Nicest way might be to show a map and highlight region selected (lots of work!)
- Not sure how to make this really clear and easy but for each practice we could indicate which lab they send their tests to and indicate that "test ordering patterns often vary by lab, so you might want to compare with other practices using same lab"

**Comment by sebbacon** [comment]
Have largely resolved this (I think) by introducing some consistency, hiding it as an option by default, and making the labels very explicit 
![image](https://user-images.githubusercontent.com/211271/76228752-0c66f580-6219-11ea-9c55-7a3663d6a7ce.png)
