### ISSUE TITLE
The data table should be documented

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#179]
It intimidated everyone. There should be some text explaining what it is, and what the columns mean.

**Comment by HelenCEBM** [comment]
agree with this; several users looked at it but weren't clear why it was there, particularly as it wasn't really possible to view the data how they might want to (e.g. just their practice). 

Could rename the tab "download data" instead?

**Comment by HelenCEBM** [comment]
Also put the download button at the top of the table (as well as bottom?) to make it more obvious that's mostly what it's for and to make this option easier to find.
