### ISSUE TITLE
Consider inverting the colour scale on heatmap

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openpath-dash#183]
It is probably more intuitive to have the darker shade indicating a higher number. However only one person pointed this out.

**Comment by sebbacon** [comment]
I don't know, I think blue as cold and yellow as warm!

Do you think any of the others here would be obviously better?
https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html

If not, let's close this one

**Comment by HelenCEBM** [comment]
We're not convinced that there's a better option that would be intuitive to everyone... like you say, typically a "heat" map goes from black (absence of heat/light) through red to white (most possible heat/light), so inverting the scale might also be confusing. Scales mostly covering blue and yellow are the most colour-blindness friendly, so not sure it's a great idea to switch. The only option I'd try is brewer-blue-green-yellow and invert. But happy to close it
