### ISSUE TITLE
Rename  “non-numeric result”

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openpath-dash#186]
This was misunderstood to mean descriptive or comment-type results, so we should make it more clear it means haemolysed/rejected samples

**Comment by sebbacon** [comment]
It's not though. It's "non-numeric". It *does* include descriptive or comment-type results.  Perhaps we should hide it because it's such a mix of things. It's really just useful for tracking down oddnesses. In the case of Potassium it *is* usually haemolysed.

**Comment by HelenCEBM** [comment]
In practice I don't think it includes many descriptive or comment results because we have excluded those tests, right? However, it's not necessarily a useful thing to select (provided you can still see results split by result type) so perhaps removing is a good idea.

**Comment by sebbacon** [comment]
I've decided to remove "no ref range" filter too on the same grounds
