### ISSUE TITLE
Create a home page

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#20]
Currently going to `/` doesn't work

**Comment by sebbacon** [comment]
Doing this nicely is a pain. I'm just making notes here about why in the hope it inspires me to a better solution.

Making a standard Flask/Jinja page appear at `/` is easy enough.

The tricky bit is when you think about mixing standard templates with a Dash app and you want them to share a common look and feel.

The problem is that the Dash framework wants control over the outermost HTML, so it can wrap it in javascript and the requisite divs and such.

The only way to include raw HTML in a Dash layout is something like [this](https://github.com/plotly/dash-dangerously-set-inner-html), but this doesn't generate a Dash HTML element tree for its children so no subelements can be targetted by callbacks.

I have tried a different approach which is to write code to convert the raw HTML in the `base.html` template into Dash HTML elements.  However, as Dash wants to create the header and all its script and style links, you can't just use it as-is.

The direction this is heading is for me to factor out the navigation and footer elements of the base template into their own sub templates, and turn *them* into Dash elements, and include them in Flask/Jinja templates.  This will probably work but it was making me sad yesterday.

The alternatives are:

* Run Dash in an iframe (but I don't think this will work as we need access to the location bar)
* Drop the idea of using normal Flask views for static pages and do it all in Dash

The problem with the latter idea is that Dash sucks for static pages, involving a load of javascript and DOM manipulation just to show some text and images. It is also nice to be able to use plain HTML for things like FAQs so the rest of the team can edit them in Github,

**Comment by evansd** [comment]
I can't link directly to the relevant section (because it's a dash app!) but have you seen section titled "Customizing Dash's HTML Index Template" on this page: https://dash.plot.ly/external-resources
