### ISSUE TITLE
Need to think about wording for "proportion of other tests"

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#31]
Further discussion needed. Couple of comments:

> I wonder if the word ‘proportion’ in ‘proportion of other tests’ is the right word as it looks like the result is a ratio?

and

> i think we may need to define how to get %out of range better - "proportion of other test" sounds like it should be a different one...

**Comment by sebbacon** [comment]
We should rename Raw numbers -> Absolute numbers.

For the denominator/filter question, should we combine them into one dropdown?

Something like 
* "potassium...  [numerator] ... showing the proportion out of range"
* "potassium...  [numerator] ... showing the proportion within range"
* "potassium...  [numerator] ... showing the proportion with non-numeric values"

**Comment by evansd** [comment]
Thinking about this a bit more, I really like the idea of combining the filter and denominator dropdowns. I wonder if we can actually drop the numerator/denominator terminology entirely and have something like this:
```
Select tests:
[                     ]

Showing:
 - Number of tests per 1000 patients
 - Number of tests
 - ------
 - Proportion of results within reference range
 - Proportion of results under reference range
 - Proportion of results over reference range
 - Proportion of results where no reference range available
 - Proportion of non-numeric results
 - ------
 - Compared with other tests
```
And then if you select the "compare" option the selector which appears has a label like:
```
Ratio of Potassium tests to:
[                             ]
```
Combined with the new layout and some reasonably explanatory chart titles I think this could be quite an intuitive interface.

**Comment by sebbacon** [comment]
Yes, this sounds great!
