### ISSUE TITLE
Display x axis at top as well as bottom of heatmap

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openpath-dash#42]
.. or if tricky, include month in popup on hover

**Comment by evansd** [comment]
This isn't possible with plot.ly at the moment (see [issue here](https://community.plot.ly/t/mirror-axis-x-bottom-and-top-y-left-and-right/7698/3)). We can mirror the x-axis ticks easily enough but they don't have any labels which makes them pretty useless as far as I can see.

Including the month in the hoverinfo sounds sensible. I wonder if it would also make sense to move the x-axis to the top, as you often won't see the bottom of the heatmap until you scroll down.

**Comment by evansd** [comment]
Possibly fixed by #78, but I think we should consider moving the x-axis labels to the top of the heatmap in any case.
