### ISSUE TITLE
Make heatmap sorting explicit / more useful

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#47]
* When grouped by practice, allow sorting by CCG
* Otherwise, only sorting by average recent values but make it clear that is what's going on, perhaps by adding the option to reverse the sort by recent values?

**Comment by sebbacon** [comment]
@evansd I know we discussed, but I can't remember - can you remind me why this is blocked?

**Comment by evansd** [comment]
Nothing major. I've got a [branch](https://github.com/ebmdatalab/openpath-dash/compare/heatmap-sorting) which has most of the work done. It's just a case of:
 1. getting the actual sort working (I can't quite get my head around what the current Pandas code is doing);
 2. figuring out where the dropdown should sit in the UI and getting it to sit there.

**Comment by sebbacon** [comment]
Let's finish this if it's not going to be more than a couple of hours work, otherwise park it.
