### ISSUE TITLE
It should be possible to download practice-level data

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#51]
We could generate a per-datatable file per [this comment](https://community.plot.ly/t/allowing-users-to-download-csv-on-click/5550/9) but alternatively, we could just make the entire CSV downloadable and document what the fields mean.

The drawback to the latter suggestion is most people won't have the skills to filter it outside a spreadsheet.  The former suggestion is a fairly thin wrapper around that so perhaps that's what we should do.

**Comment by evansd** [comment]
Quick note to self on the above. I think this should be reasonably straightforwardly do-able by:
 * serializing as a JSON string the arguments we pass into `get_count_data` here https://github.com/ebmdatalab/openpath-dash/blob/ad520fb4d7e74c6adc5fb4cade8314c481323cb1/apps/datatable.py#L31-L38
 * Creating a download link beneath the data table whose href is computed from `page_state` and is set to `/download?spec=[JSON]`
 * Creating a Flask `/download` endpoint which deserializes `spec`, passes the arguments to `get_count_data` and returns the resulting dataframe as CSV.
