### ISSUE TITLE
Highlighted entities should be sticky when switching away from grouping and back again

### ISSUE THREAD

**Issue by alexwalkerepi** [ebmdatalab/openpath-dash#71]
Navigating to this page:
http://dash.openpathology.net/data/chart/by/ccg_id/showing/ccg_id/all/numerators/K/denominators/K/filter/over_range?highlight_entities=11N&highlight_entities=15N

...gives highlighted entities for `15N` and `11N`, but if you then change the `Group by` to `Practice`, then back to `CCG`, the highlighted entities disappear.

While I've since worked out that you can get them back by clicking on the relevant heatmap, it wasn't that intuitive and people might find it a bit annoying if they had a few entities selected.

**Comment by sebbacon** [comment]
We should only do this if it's easy. I suppose it will need cookies.
