### ISSUE TITLE
Error when grouping by result type

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#82]
500 caused when here http://dash.openpathology.net/data/chart/by/result_category/showing/ccg_id/all/numerators/TSH/denominators/TSH/filter/under_range?highlight_entities=11N&highlight_entities=15N

**Comment by HelenCEBM** [comment]
I grouped by result type, then changed the choice of CCGs to be shown, then changed to group by CCG, then changed back to group by result type and ended up with a few conflicts:
![image](https://user-images.githubusercontent.com/24392156/69817365-57bd4100-11f2-11ea-8b3d-a67f4ad3a30b.png)


http://dash.openpathology.net/data/chart/by/result_category/showing/ccg_id/all/numerators/BASO/denominators/per1000/filter/all?highlight_entities=15N

**Comment by sebbacon** [comment]
Related to #84 ?

**Comment by sebbacon** [comment]
So the combination of both selecting from the heatmap *and* filtering CCGs seems to break things; possibly it's also not removing the selected CCG when you change the `groupby` or the `showing`

**Comment by sebbacon** [comment]
Notes to self...

In terms of code, what I want to do is:
* When the page_state changes, delete the query string if the grouby changes
* The problem is that we already change the query string in the heatmap function, and you can't have the same output twice
