### ISSUE TITLE
CCG filter not working? 

### ISSUE THREAD

**Issue by HelenCEBM** [ebmdatalab/openpath-dash#84]
Looking at Basophil tests per 1000 population, by result type:
http://dash.openpathology.net/data/chart/by/result_category/showing/ccg_id/15N/numerators/BASO/denominators/per1000/filter/all?highlight_entities=0&highlight_entities=1&highlight_entities=-1

Changing the CCG selection doesn't change the chart.

**Comment by sebbacon** [comment]
We think this is showing *all* the data and it's related to the `highlight_entities` parameter being sticky and having unexpected effects.
