### ISSUE TITLE
Raw data download broken in some cases

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openpath-dash#89]
I believe where the denominator is `all` ([ex](http://dash.openpathology.net/data/datatable/by/test_code/showing/ccg_id/all/numerators/all/denominators/all/filter/2))

**Comment by evansd** [comment]
I can't reproduce this. The linked page gives an "Unable to find page" error before I can try to download anything. I've tried generating a chart locally where the denominator is "all" and I seem to be able to download data OK.

**Comment by sebbacon** [comment]
The URL scheme had changed since I posted the issue - it's not just denonminator `all` but also filter `2`: http://dash.openpathology.net/data/datatable/by/test_code/showing/ccg_id/all/lab_id/all/numerators/all/denominators/all/filter/2

Inspecting traffic shows a 500 being returned.
