### ISSUE TITLE
Downloading plots from dashboard

### ISSUE THREAD

**Issue by jackosullivanoxford** [ebmdatalab/openpath-dash#92]
The 'download plot' feature on http://dash.openpathology.net/data/chart doesn't mimic the graph one sees on the website. For instance, the heatmap figure, when downloaded as a .png is very vertically squashed it is essentially uninterpretable. The decile graph is also restricted and not quite a good as the decile graph you actually see on the website, although it is interpretable

**Comment by sebbacon** [comment]
Having trouble reproducing this for deciles.

Taking [this page](http://dash.openpathology.net/data/chart/by/practice_id/showing/ccg_id/all/lab_id/all/numerators/CREA/denominators/per1000/filter/all?highlight_entities=130&highlight_entities=63) as an example, I get this for the deciles:

![image](https://user-images.githubusercontent.com/211271/70033203-e3deb800-15a6-11ea-938f-3fd9a4d8d64e.png)

For heatmap I can reproduce:

![image](https://user-images.githubusercontent.com/211271/70033275-08d32b00-15a7-11ea-938b-d0f73266bbd1.png)

**Comment by sebbacon** [comment]
Note to whoever fixes this - [this thread](https://community.plot.ly/t/save-plot-as-png-sizing-and-positioning/10166/5) looks useful

**Comment by jackosullivanoxford** [comment]
Yep for both graphs that is what I was viewing. Clearly the heatmap is the more pressing issue, but the decile graph condenses from presenting x-axis tics 6-monthly to yearly. See below two images: image (a) is the downloaded plot, and image (b) is the screenshot of what is actually on the website. This is a small thing that we might not feel needs to be changed, but I just wanted to flag it because it was something I noticed (as a user). 

Image (a)
![newplot (2)](https://user-images.githubusercontent.com/35063801/70065439-fbff0900-159f-11ea-9d69-cc77e7cfd9e9.png)

Image (b)
<img width="1047" alt="Screen Shot 2019-12-03 at 7 37 50 AM" src="https://user-images.githubusercontent.com/35063801/70065467-07eacb00-15a0-11ea-90d9-7031aa219e9a.png">
